services:
  app:
    image: jae:local
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped